Editando yapu

diff --git a/yapu b/yapu
--- a/yapu
+++ b/yapu
@@ -1,12 +1,13 @@
 #!/bin/sh
+#!/bin/sh
 ### Yapu v 2 ( Yet Another Puppy Usb Installer )
-### A script (under developmet) to make bootable USB from recent puppies, 
+### A script (under developmet) to make bootable USB from recent puppies,
 ### and maybe other distros
 ### Use grub4dos, bootlace.com, advcpmv ( advanced copy move from coreutils )
 ### GPL3
 
 ### How does it works?
-#1- List partitions 
+#1- List partitions
 #2- Check necessary files
 #3- Format usb
 #4- Install bootlace.com
@@ -36,36 +37,36 @@ echo ""
 fdisk -l |grep "^\/dev\/" |awk '{print $1, $2}'
 echo ""
 echo ""
-#fdisk -l |grep -e '^/' |awk '{print $1}'|sed -e "s|/dev/||g"  OTHER METHOD
-#fdisk -l 2>/dev/null | egrep  '(/dev/[^:]*):' | egrep '([^:]*)' OTHER METHOD
+#fdisk -l |grep -e '^/' |awk '{print $1}'|sed -e "s|/dev/||g" OTHER METHOD
+#fdisk -l 2>/dev/null | egrep '(/dev/[^:]*):' | egrep '([^:]*)' OTHER METHOD
 
 ############ item 2 ##############
 
 if [ -f "$GRLDR" ]; then
  echo""
- echo -e "$(gettext '  \e[93m Grldr already exist, it will copy to /tmp/grub4dos\e[0m')" 
+ echo -e "$(gettext ' \e[93m Grldr already exist, it will copy to /tmp/grub4dos\e[0m')"
  echo ""
  mkdir /tmp/grub4dos && cp $GRLDR $TMP
-else if [ ! -f "$GRLDR" ]; then 
- echo -e "$(gettext '  \e[91m Grldr is missing, downloading and copying to /tmp/gru4dos...\e[0m')"
+else if [ ! -f "$GRLDR" ]; then
+ echo -e "$(gettext ' \e[91m Grldr is missing, downloading and copying to /tmp/gru4dos...\e[0m')"
  echo ""
   wget -c --no-check-certificate https://copy.com/RauOYpR0XZ2Z/grldr -P /tmp/grub4dos
   fi
 fi
 if [ -f "$SPLASH" ]; then
  echo ""
- echo -e "$(gettext '  \e[93m splash.xpm already exist, it will copy to /tmp/grub4dos\e[0m')" 
+ echo -e "$(gettext ' \e[93m splash.xpm already exist, it will copy to /tmp/grub4dos\e[0m')"
  echo ""
  cp $SPLASH $TMP
-else if [ ! -f "$SPLASH" ]; then 
- echo -e "$(gettext '  \e[91m Splash.xpm is missing, downloading and copying to /tmp/gru4dos....\e[0m')"
+else if [ ! -f "$SPLASH" ]; then
+ echo -e "$(gettext ' \e[91m Splash.xpm is missing, downloading and copying to /tmp/gru4dos....\e[0m')"
  echo ""
  wget --no-check-certificate https://copy.com/JbVWsDTAgkno/splash.xpm -P /tmp/grub4dos
   fi
 fi
 if [ ! -f "$MKFSVFAT" ]; then
 echo -e "$(gettext '\e[93m This script requires mkfs.vfat in /usr/sbin\e[0m')"
-	exit 1
+exit 1
 fi
 if [ ! -f "$BOOTLACE" ]; then
 echo -e "$(gettext '\e[93m This script requires bootlace.com in /usr/sbin\e[0m')"
@@ -73,7 +74,7 @@ echo -e "$(gettext '\e[93m This script requires bootlace.com in /usr/sbin\e[0m')
 fi
 if [ ! -f "$ADVCPMV" ]; then
  echo ""
- echo -e "$(gettext '  \e[91m This script requires advcpmv, downloading and installing...\e[0m')" 
+ echo -e "$(gettext ' \e[91m This script requires advcpmv, downloading and installing...\e[0m')"
  echo ""
   wget -c --no-check-certificate https://copy.com/b9sjvs0hM8MC/advcpmv.tar.gz -P ~/
   tar xvzf ~/advcpmv.tar.gz -C /usr/local/bin/ && chmod +x /usr/local/bin/advcpmv/*
@@ -118,13 +119,12 @@ mkdir -p /mnt/isoimage
 sleep 2
 mount -t iso9660 -o loop $ISO /mnt/isoimage
 echo
-printf "$(gettext '      \e[34m Now Working...\e[0m')" 
+printf "$(gettext ' \e[92m Now Working...\e[0m')"
 echo ""
 echo ""
 
 ########### item 7 #############
 
-UUID=`blkid $USB | sed 's/.*UUID/uuid/g;s/ TYPE.*//g'`
 
 cat > /mnt/media/menu.lst <<EOF
 # menu.lst produced by grub4dosconfig-v1.8.0
@@ -136,57 +136,57 @@ default 0
 # Frugal installed Puppy
 
 title Puppy $MYDIR
-  $UUID
-  kernel /$MYDIR/vmlinuz   psubdir=$MYDIR pmedia=usbflash pfix=fsck
-  initrd /$MYDIR/initrd.gz
-  
+kernel /$MYDIR/vmlinuz psubdir=$MYDIR pmedia=usbflash pfix=fsck
+initrd /$MYDIR/initrd.gz
+
 # Windows
 # this entry searches Windows on the HDD and boot it up
 title Windows\nBoot up Windows if installed
-  map (hd1) (hd0)
-  map (hd0) (hd1)
-  map --hook
-  errorcheck off
-  find --set-root --ignore-floppies --ignore-cd  /bootmgr
-  chainloader /bootmgr
-  find --set-root --ignore-floppies --ignore-cd  /ntldr
-  chainloader /ntldr
-  find --set-root --ignore-floppies --ignore-cd   /io.sys
-  chainloader /io.sys
-  errorcheck on
+map (hd1) (hd0)
+map (hd0) (hd1)
+map --hook
+errorcheck off
+find --set-root --ignore-floppies --ignore-cd /bootmgr
+chainloader /bootmgr
+find --set-root --ignore-floppies --ignore-cd /ntldr
+chainloader /ntldr
+find --set-root --ignore-floppies --ignore-cd /io.sys
+chainloader /io.sys
+errorcheck on
 EOF
 
 /usr/local/bin/advcpmv/cp /tmp/grub4dos/grldr /mnt/media/
 /usr/local/bin/advcpmv/cp /tmp/grub4dos/splash.xpm /mnt/media/
 chmod +x /mnt/media/grldr
 cd /mnt/isoimage
-/usr/local/bin/advcpmv/cp vmlinuz initrd.gz /mnt/media/$MYDIR
-/usr/local/bin/advcpmv/cp *.sfs /mnt/media/$MYDIR
-cd /mnt/media/$MYDIR
-ls -l 
+/usr/local/bin/advcpmv/cp -g -v vmlinuz initrd.gz /mnt/media/$MYDIR
+/usr/local/bin/advcpmv/cp -g -v *.sfs /mnt/media/$MYDIR
+md5sum *.sfs
+cd /mnt/media/
+ls -l
 echo ""
 echo -e "$(gettext ' \e[93m If all is ok, you will see 4 files in the usb device\e[0m')"
 echo ""
 echo -e "$(gettext ' \e[93m grldr, your custom directory, menu.lst and splash.xpm\e[0m')"
 echo ""
-cd 
+cd
 
 ################### item 8 #############################
 
-echo -ne "$(gettext '\e[92m Is all ok?,') [y/n]    \e[0m"
+echo -ne "$(gettext '\e[92m Is all ok?,') [y/n] \e[0m"
 echo ""
-read OK 
+read OK
 if [ "$OK" == "y" ]; then
-echo "" 
-printf "$(gettext '  \e[93m Cleaning up...\e[0m')" 
+echo ""
+printf "$(gettext ' \e[93m Cleaning up...\e[0m')"
 echo ""
 umount -r /mnt/media
 umount -r /mnt/isoimage
-rm -r /tmp/grub4dos
+rm -R /tmp/grub4dos
 rm -r ~/advcpmv.tar.gz
-rm -r /usr/local/bin/advcpmv
+rm -R /usr/local/bin/advcpmv
 echo ""
-echo -e "$(gettext ' \e[34m Done.... \e[0m')"
+echo -e "$(gettext ' \e[92m Done.... \e[0m')"
 echo ""
 echo ""
 else exit 1
